### Usuário autenticado
GET http://127.0.0.1:8000/auth/token 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZmVsaXBlIn0.ZFyBuwnzsGt0_tJpi06WuPR-1Yu7rEQXxwfdqZUXrXdh6KgYXQfabSZg_ogD2-0TC_cl3d8TEdHCeEGrW11gBI7j3UKONOdlhSzWbloQhPgWI-sTvinJnB00B9Q-JweOpn6tivmov8nDbOL0p2fbETCspNY87J__yas18eTISR874Yc4aLVNfA7N8zXCbgft8KMN00jEOIa0GTWe4vvV1A2YPNJoqIS4LhxJzaVFlusc7cSkVrXArocV94tnc2YjO0XCBu1Vq6K1AGLXegQbLk5CVUVFBhhx5MGWCPEpt7tYdYaaO877NU2uFQ1HwVnNl4w2QKKaMHB6KRzZdP-XnA


### Usuário autenticado com autorização
GET http://127.0.0.1:8000/muda/produto 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZmVsaXBlIiwicGVybWlzc29lcyI6ImFkbWluIn0.UgagcQrgKoNJCesbPebcM4w-lTza3tY6ZDnY_TOLUjieZ8crpZqtNJt_XezKOaIoT_uMmVlM_Og4FOVKagO6175lAGr-YR_62IsSvtEycwi_5rw0WFy619l813OebqlmtrK6AEjpUzcX5kqDXxC0T4etv7okNwumlgJtVdh8TIzOTK5Y0tMnaN5RCnYs5sKeRYAMXNNz3_Gx74XHTsDYe_SoobHM_4rKnGFEiwVd1nwC7Idzfm6UwAkhQnaw7M-esfNFgXMbss-M022Xai-y0FNrR_xacGeis69JbrBiiL6vUD_1pHsFbO60HWVaG6aVa88-OXmE8uTi3HJ_D0vcWw


### Token com erro na assinatura
GET http://127.0.0.1:8000/muda/produto 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZmVsaXBlIiwicGVybWlzc29lcyI6ImFkbWluIn0.UgagcQrgKoNJCesbPebcM4w-lTza3tY6ZDnY_TOLUjieZ8crpZqtNJt_XezKOaIoT_uMmVlM_Og4FOVKagO6175lAGr-YR_62IsSvtEycwi_5rw0WFy619l813OebqlmtrK6AEjpUzcX5kqDXxC0T4etv7okNwumlgJtVdh8TIzOTK5Y0tMnaN5RCnYs5sKeRYAMXNNz3_Gx74XHTsDYe_SoobHM_4rKnGFEiwVd1nwC7Idzfm6UwAkhQnaw7M-esfNFgXMbss-M022Xai-y0FNrR_xacGeis69JbrBiiL6vUD_1pHsFbO60HWVaG6aVa88-OXmE8uTi3HJ_D0vcWb


### Usuário autenticado sem autorização
GET http://127.0.0.1:8000/muda/produto 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZmVsaXBlIiwicGVybWlzc29lcyI6InVzdWFyaW8ifQ.QJQ9tkj7W-SpyxLQIb31O6SsZfHQTH0x7HTc-sjGlHJrZWh3VFaZS9KYEtrYMzyxB_ikNLs1yGcY1TeCpGhmb8-ZNpVAgUGX6ro7z8vq9yfMxS3HaxZ01W5XAcv3IyDIRDEK8yxV05XAUu3g1ngufRiD7NvNw0Z9YoK1YagaMX2wzMZiZwU_afpqWwPqmKSuOssg3GG0CI1bo0wBwffKuEFSNtHwqEZ1tX2C9wnLDcYNkeopNetmaHKPUTJi20OBLV3zD97UnoKo138hy8dsAgqvrZRgRpaaAGIbynqL_L4enube2sC1fuNjwAD8ooRmmu66FDk1sTLHBwY_dtCA2g


